apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: prometheus
  namespace: monitoring
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: prometheus
  template: 
    metadata: 
      labels: 
        app: prometheus
    spec:
      containers: 
      - name: prometheus-container 
        image: prom/prometheus 
        ports: 
          - containerPort: 9090 
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--storage.tsdb.path=/prometheus"
          - "--web.enable-otlp-receiver"   # OTLP receiver 활성화
          - "--web.listen-address=:9090"
          - "--web.route-prefix=/"
        volumeMounts: 
        - name: prometheus-config 
          mountPath: /etc/prometheus/prometheus.yml 
          subPath: prometheus.yml
      volumes: 
      - name: prometheus-config 
        configMap: 
          name: prometheus-config