apiVersion: v1 
kind: Service 
metadata: 
  name: prometheus-svc
  namespace: monitoring
spec: 
  ports: 
  - name: prometheus-port 
    port: 9090 
    targetPort: 9090 
  selector: 
    app: prometheus